### ISSUE TITLE
Semantic segmentation with guided diffusion backbone

### ISSUE THREAD

**Issue by jn-kim** [soumik-kanad/diffssl#4]
Hello, thank you for your excellent work.
I would like to re-implement the performance of ADE20K semantic segmentation with Upernet mentioned in the paper. Could you please provide the code for applying the guided diffuson backbone on MAE with mmsegmentation framework?
Thank you.

**Comment by soumik-kanad** [comment]
Sorry for late reply. We will try to add the code soon.
