### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by 213pk** [soumik-kanad/diffssl#6]
How can I evaluate the model? It seems like you only provided the code for training. Thanks!

**Comment by soumik-kanad** [comment]
The code automatically evaluates during training and both prints it as well as pushes it on wand. Check test() function in finetune.py. 

(You may also explore the eval_only flag if you want to evaluate after training.)

**Comment by zhd61** [comment]
Will you please provide the pre-trained checkpoints?

**Comment by soumik-kanad** [comment]
@zhd61 I'm slightly busy right now. Will try to provide checkpoints soon.
