### ISSUE TITLE
Input feature size

### ISSUE THREAD

**Issue by 213pk** [soumik-kanad/diffssl#8]
What is the detailed size of your input feature before feeding into the DifFeed? Thanks.

**Comment by soumik-kanad** [comment]
In our default setting in [feedback.sh](https://github.com/soumik-kanad/diffssl/blob/main/scripts/feedback.sh) we use blocks [21,24,27,30,33,36] (we have numbered the blocks starting from 1) which are the bottleneck blocks (after which the feature resolutions change) in the decoder. 

Here are the shapes of inputs the the DifFeed layers - 
`21 torch.Size([1, 1024, 8, 8])`
`24 torch.Size([1, 1024, 16, 16]) `
`30 torch.Size([1, 512, 64, 64])`
`33 torch.Size([1, 256, 128, 128])`
`36 torch.Size([1, 256, 256, 256])`

You can find all these calculations being done in [this line of code](https://github.com/soumik-kanad/diffssl/blob/cc2ac303c1fc02302d684c9d62895f273a3c2615/ssl_diff/ssl_model_feedback_fusion.py#L126).

**Comment by soumik-kanad** [comment]
For comparison here are the output shapes of all the blocks of the unconditional Guided Diffusion (aka ADM) model 
And you can find these in our [const.py](https://github.com/soumik-kanad/diffssl/blob/cc2ac303c1fc02302d684c9d62895f273a3c2615/ssl_diff/const.py#L7)

```
1 torch.Size([1, 256, 256, 256])
2 torch.Size([1, 256, 256, 256])
3 torch.Size([1, 256, 256, 256])
4 torch.Size([1, 256, 128, 128])
5 torch.Size([1, 256, 128, 128])
6 torch.Size([1, 256, 128, 128]) 
7 torch.Size([1, 256, 64, 64])
8 torch.Size([1, 512, 64, 64])
9 torch.Size([1, 512, 64, 64])
10 torch.Size([1, 512, 32, 32])
11 torch.Size([1, 512, 32, 32])
12 torch.Size([1, 512, 32, 32])
13 torch.Size([1, 512, 16, 16])
14 torch.Size([1, 1024, 16, 16])
15 torch.Size([1, 1024, 16, 16])
16 torch.Size([1, 1024, 8, 8])
17 torch.Size([1, 1024, 8, 8])
18 torch.Size([1, 1024, 8, 8])
19 torch.Size([1, 1024, 8, 8])
20 torch.Size([1, 1024, 8, 8])
21 torch.Size([1, 1024, 8, 8])
22 torch.Size([1, 1024, 16, 16])
23 torch.Size([1, 1024, 16, 16])
24 torch.Size([1, 1024, 16, 16])
25 torch.Size([1, 1024, 32, 32])
26 torch.Size([1, 512, 32, 32])
27 torch.Size([1, 512, 32, 32])
28 torch.Size([1, 512, 64, 64])
29 torch.Size([1, 512, 64, 64])
30 torch.Size([1, 512, 64, 64])
31 torch.Size([1, 512, 128, 128])
32 torch.Size([1, 256, 128, 128])
33 torch.Size([1, 256, 128, 128])
34 torch.Size([1, 256, 256, 256])
35 torch.Size([1, 256, 256, 256])
36 torch.Size([1, 256, 256, 256])
37 torch.Size([1, 256, 256, 256])
```
